name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build database and metadata
        run: |
          python build_database.py

      - name: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |-
          export LATEST_DATASETTE=`curl -s "https://api.github.com/repos/simonw/datasette/commits/main" | jq -r .sha`
          datasette install datasette-publish-fly
          datasette publish fly cmip6-downscaling.db --app carbonplan-datasette \
           -m metadata.json \
           --extra-options='--setting max_returned_rows 3000' \
           --install=datasette-jellyfish \
           --install=datasette-graphql \
           --install='datasette-copyable>=0.2' \
           --install=datasette-nteract-data-explorer \
           --install datasette-search-all \
          #  --install=datasette-dashboards \
          #  --install=datasette-export-notebook \
          #  --install=datasette-vega \
           --version-note=$LATEST_DATASETTE \
           --branch=$LATEST_DATASETTE
