name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Download data
        env:
          BUCKET: 'https://carbonplan-share.s3.us-west-2.amazonaws.com/datasette/cmip6-downscaling'
        run: |
          mkdir -p data && cd data
          curl --remote-name-all "$BUCKET/CMIP.CCCma.CanESM5.historical.day.DeepSD-BC.csv.gz $BUCKET/CMIP.BCC.BCC-CSM2-MR.historical.day.GARD-SV.csv.gz"

      - name: List downloaded data
        run: |
          ls -ltrh data

      - name: Create database
        run: |
          csvs-to-sqlite data/*.csv.gz cmip6-downscaling.db
          sqlite-utils analyze-tables cmip6-downscaling.db --save

      - name: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |-
          export LATEST_DATASETTE=`curl -s "https://api.github.com/repos/simonw/datasette/commits/main" | jq -r .sha`
          datasette install datasette-publish-fly
          datasette publish fly cmip6-downscaling.db --app carbonplan-datasette \
           --extra-options='--setting max_returned_rows 10000' \
           --install=datasette-vega \
           --install=datasette-jellyfish \
           --install=datasette-graphql \
           --install='datasette-copyable>=0.2' \
           --version-note=$LATEST_DATASETTE \
           --branch=$LATEST_DATASETTE
